// <auto-generated />
using System;
using Cliqlearn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cliqlearn.Migrations
{
    [DbContext(typeof(CliqDBContext))]
    [Migration("20240714110824_coaa")]
    partial class coaa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cliqlearn.Models.College", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("college_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("college_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("colleges");
                });

            modelBuilder.Entity("Cliqlearn.Models.CollegeStudent", b =>
                {
                    b.Property<int>("CollegeStudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("collegeid")
                        .HasColumnType("int");

                    b.Property<int?>("studentid")
                        .HasColumnType("int");

                    b.HasKey("CollegeStudentId");

                    b.HasIndex("collegeid");

                    b.HasIndex("studentid");

                    b.ToTable("CollegeStudent");
                });

            modelBuilder.Entity("Cliqlearn.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("Cliqlearn.Models.CollegeStudent", b =>
                {
                    b.HasOne("Cliqlearn.Models.College", "college")
                        .WithMany()
                        .HasForeignKey("collegeid");

                    b.HasOne("Cliqlearn.Models.Student", "student")
                        .WithMany("college")
                        .HasForeignKey("studentid");

                    b.Navigation("college");

                    b.Navigation("student");
                });

            modelBuilder.Entity("Cliqlearn.Models.Student", b =>
                {
                    b.Navigation("college");
                });
#pragma warning restore 612, 618
        }
    }
}
